version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install awscli cfn-lint
  build:
    commands:
      - aws cloudformation validate-template --template-body file://core.yaml
      - cfn-lint core.yaml
artifacts:
  files:
    - core.yaml
