AWSTemplateFormatVersion: 2010-09-09
Description: "CI CD pipeline"
Resources:
  CdkAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CdkAdminPassRole
                Effect: Allow
                Action:
                  - "iam:PassRole"
                  - "iam:GetRole"
                Resource: "*"
          PolicyName: PassRolePolicy
